name: Java application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: "11"

    - name: Build with Maven
      run: |
        mvn clean install
    - name: Create artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-publish-app-artifact
        path: target/

  deploy:
  
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: java-publish-app-artifact

      - name: Set up SSH
        env:
          DEPLOY_KEY: ${{ secrets.SENAC_AZURE_VM }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 172.191.64.68 >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          DEPLOY_KEY: ${{ secrets.SENAC_AZURE_VM }}
        run: |
          scp -i ~/.ssh/id_rsa -r ./java-publish-app-artifact/* azureadmin@172.191.64.68:/app/data/
